services:
  - type: web
    name: taskflow
    env: docker # ← change ça !
    dockerfilePath: ./Dockerfile
    # Pas besoin de buildCommand/startCommand car dans le Dockerfile
    envVars:
      - key: APP_NAME
        value: TaskFlow
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true # ou mets ta vraie clé si tu préfères
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      # Ajoute ta DB si tu en as une sur Render
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: ton-db-postgres
      #     property: connectionString
